config/routes.rb
Rails.application.routes.draw do
  resources :events do
    get :search, on: :collection
  end

  root 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :start_datetime, presence: true
  validates :end_datetime, presence: true
  validates :prefecture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @events = Event.all
    @keyword = params[:keyword]
    @start_date_from = params[:start_date_from]
    @start_date_to = params[:start_date_to]
    @prefecture_to = params[:prefecture_to]
    @events = @events.where('title LIKE ?', "%#{@keyword}%") if @keyword.present?
    @events = @events.where('prefecture = ?', "#{@prefecture_to}") if @prefecture_to.present?
    if @start_date_from.present? && @start_date_to.present?
      @events = @events.where(start_datetime: "#{@start_date_from}".."#{@start_date_to+' 23:59:59'}")
    elsif @start_date_from.present?
        @events = @events.where('start_datetime >= ?',"#{@start_date_from}")
    elsif @start_date_to.present?
        @events = @events.where('start_datetime <= ?',"#{@start_date_to +' 23:59:59'}")
    end
    flash.now[:notice] = "イベントは見つかりませんでした" if @events.blank?
    render "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_datetime, :end_datetime, :prefecture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title,"タイトル" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_datetime,"開催日時" %>
    <%= form.datetime_select :start_datetime %>
  </div>

  <div class="field">
    <%= form.label :end_datetime,"終了日時" %>
    <%= form.datetime_select :end_datetime %>
  </div>

  <div class="field">
    <%= form.label :prefecture, "開催エリア" %>
    <%= form.select(:prefecture, options_for_select([[''],['東京都'], ['大阪府'],['神奈川県'],['愛知県'] ])) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_search_form.html.erb
<div class="search-form">
  <%= form_with url: search_events_path, method: :get, local: true do |f| %>
    <%= f.label :keyword, "キーワード" %>
    <%= f.text_field :keyword, value: @keyword %>

    <%= f.label :start_date_from, "開催日" %>
    <%= f.date_field :start_date_from, value: @start_date_from %>  〜
    <%= f.date_field :start_date_to, value: @start_date_to %>

    <%= f.label :prefecture_to, "開催エリア" %>
    <%#= f.text_field :prefecture_to, value: @prefecture_to %>
    <%= f.select(:prefecture_to, options_for_select([[''],['東京都'], ['大阪府'],['神奈川県'],['愛知県'] ], selected: @prefecture_to)) %>
    <%= f.submit "検索" %>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= render 'search_form' %>

<br>
<%= link_to 'New Event', new_event_path %>
<br>
<br>
<% if @events.present? %>
  <table>
    <thead>
      <tr>
        <th>タイトル</th>
        <th>開催日時</th>
        <th>終了日時</th>
        <th>開催エリア</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.title %></td>
          <td><%= event.start_datetime %></td>
          <td><%= event.end_datetime %></td>
          <td><%= event.prefecture %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <strong>イベントが見つかりません</strong>
<% end %>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/search.html.erb
<%# <p id="notice"><%= notice %></p> %>

<!-- <h1>Events</h1> -->

<%# <%= render 'search_form' %> %>

<!-- <table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>開催日時</th>
      <th>終了日時</th>
      <th>開催エリア</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <!-- <tbody> -->
    <%# <% @events.each do |event| %> %>
      <!-- <tr> -->
        <!-- <td> -->
          <%# <%= event.title %> %>
        <!-- </td> -->
        <!-- <td> -->
          <%# <%= event.start_datetime %> %>
        <!-- </td>
        <td> -->
          <%# <%= event.end_datetime %> %>
        <!-- </td>
        <td> -->
          <%# <%= event.prefecture %> %>
        <!-- </td>
        <td> -->
          <%# <%= link_to 'Show', event %> %>
        <!-- </td>
        <td> -->
          <%# <%= link_to 'Edit', edit_event_path(event) %> %>
        <!-- </td>
        <td> -->
          <%# <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %> %>
        <!-- </td> -->
      <!-- </tr> -->
    <%# <% end %> %>
  <!-- </tbody> -->
<!-- </table> -->

<!-- <br> -->

<%# <%= link_to 'Back', events_path %> %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>開催日時:</strong>
  <%= @event.start_datetime %>
</p>

<p>
  <strong>終了日時:</strong>
  <%= @event.end_datetime %>
</p>

<p>
  <strong>開催エリア:</strong>
  <%= @event.prefecture %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleNarrowDownSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>